---
- hosts: node02
  gather_facts: yes
  tasks:
    - name: Create facts.txt
      blockinfile:
        path: /root/facts.txt
        create: yes
        block: |
          This is Ansible managed node {{ ansible_nodename }}
          IP address of host is {{ ansible_default_ipv4.address }}
          Its OS family is {{ ansible_os_family }}

    - name: Make index.html
      copy:
        src: /root/facts.txt
        remote_src: yes
        dest: /usr/share/nginx/html/index.html